name: Python CI

on:
  push:
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[run ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pytest
        run: pip install pandas numpy pytest scikit-learn mlflow xgboost

      - name: Run tests
        run: pytest tests/test.py -s -v